services:
    openproject:
        stdin_  open: true
        tty: true
        ports:
            - 8080:80
        restart: unless-stopped    
        environment:
            - OPENPROJECT_SECRET_KEY_BASE=secret
            - OPENPROJECT_HOST__NAME=localhost:8080
            - OPENPROJECT_HTTPS=false
            - OPENPROJECT_DEFAULT__LANGUAGE=en
        image: openproject/openproject:14


# version: '3'
# services:
#   openproject:
#     image: openproject/openproject:14
#     ports:
#       - "8080:80"
#     environment:
#       - OPENPROJECT_SECRET_KEY_BASE=secret
#       - OPENPROJECT_HOST_NAME=localhost:8080
#       - OPENPROJECT_HTTPS=false
#       - OPENPROJECT_DEFAULT_LANGUAGE=en
#     volumes:
#       - /var/lib/openproject/pgdata:/var/openproject/pgdata
#       - /var/lib/openproject/assets:/var/openproject/assets
